version: "3.1"

services:
  mysql:
    image: "mysql:latest"
    restart: "always"
    environment:
      - "MYSQL_ROOT_PASSWORD=your_password"
      - "MYSQL_DATABASE=kimchi_premium"
    ports:
      - "3306:3306"
